[tox]
envlist = py314,
          py313,
          py312,
          py311,
          py310,
          pylama,
          mypy,

[testenv]
deps =
    aiounittest
    pytest
    pytest-codeblocks
    pytest-cov
commands = pytest -v --codeblocks

[testenv:pylama]
basepython = python3
deps =
    pylama[pylint]
    setuptools<81
commands = pylama aiochannel tests

[testenv:mypy]
deps =
    mypy
    types-setuptools
basepython = python3
commands = mypy --non-interactive --install-types aiochannel
